In [1]:
import numpy as np

In [2]:
x=np.loadtxt("mynos.txt")
print(x)
print(np.sum(x))

[ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]
550.0


In [3]:
no = np.loadtxt("multinos.txt")
print(no)
print(np.sum(no))

[[ 10.  20.  30.  40.  50.]
 [  1.   2.   3.   4.   5.]
 [100. 200. 300. 400. 500.]]
1665.0


In [4]:
x = np.genfromtxt("wordnos.txt")
print(x)
print(np.sum(x))

[10. nan 20. nan 30. 40. nan 60. nan 70. 80.]
nan


In [5]:
x=np.genfromtxt("wordnos.txt",filling_values=0)
print(x)
print(np.sum(x))

[10.  0. 20.  0. 30. 40.  0. 60.  0. 70. 80.]
310.0


In [6]:
x=np.genfromtxt("wordnos.txt",filling_values=10)
print(x)
print(np.sum(x))

[10. 10. 20. 10. 30. 40. 10. 60. 10. 70. 80.]
350.0


In [7]:
x=np.array([100,200,300,400,500,600,700,800,900,1000])
np.savetxt("newnos.txt",x)

In [8]:
z=np.loadtxt("newnos.txt")
print(x)

[ 100  200  300  400  500  600  700  800  900 1000]
